"""add composite index on mwh revenue

Revision ID: 3561ae89f72e
Revises: bdefc5927303
Create Date: 2025-06-15 21:26:55.337753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3561ae89f72e'
down_revision: Union[str, None] = 'bdefc5927303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_mwh_revenue_timestamp_asic_id', 'mwh_revenue', ['mwh_revenue_timestamp', 'asic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mwh_revenue_timestamp_asic_id', table_name='mwh_revenue')
    # ### end Alembic commands ###
