"""add block number to mwhrevenue

Revision ID: bdefc5927303
Revises: 92c389830943
Create Date: 2025-06-15 20:21:58.324262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bdefc5927303'
down_revision: Union[str, None] = '92c389830943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asic', 'asic_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('mwh_revenue', sa.Column('block_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_mwh_revenue_block_number'), 'mwh_revenue', ['block_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mwh_revenue_block_number'), table_name='mwh_revenue')
    op.drop_column('mwh_revenue', 'block_number')
    op.alter_column('asic', 'asic_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
