"""add block numberto exchange rate

Revision ID: cdb5b609c02a
Revises: eab3865a7c6a
Create Date: 2025-06-14 15:42:20.493536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cdb5b609c02a'
down_revision: Union[str, None] = 'eab3865a7c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_rate', sa.Column('block_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_rate', 'block_number')
    # ### end Alembic commands ###
