"""add indexes

Revision ID: d817540773ca
Revises: c79849a2e841
Create Date: 2025-06-15 11:42:13.215704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd817540773ca'
down_revision: Union[str, None] = 'c79849a2e841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_block_timestamp_number', 'block_data', ['block_timestamp', 'block_number'], unique=False)
    op.create_unique_constraint(None, 'block_data', ['block_number'])
    op.create_index(op.f('ix_exchange_rate_block_number'), 'exchange_rate', ['block_number'], unique=True)
    op.create_index(op.f('ix_exchange_rate_exchange_rate_timestamp'), 'exchange_rate', ['exchange_rate_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rate_exchange_rate_timestamp'), table_name='exchange_rate')
    op.drop_index(op.f('ix_exchange_rate_block_number'), table_name='exchange_rate')
    op.drop_constraint(None, 'block_data', type_='unique')
    op.drop_index('idx_block_timestamp_number', table_name='block_data')
    # ### end Alembic commands ###
