"""add block data

Revision ID: eab3865a7c6a
Revises: 
Create Date: 2025-06-11 20:43:16.380898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'eab3865a7c6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_subsidy', sa.Float(), nullable=False),
    sa.Column('block_transaction_fees', sa.Float(), nullable=False),
    sa.Column('network_hash_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('exchange_rate_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_rate')
    op.drop_table('block_data')
    # ### end Alembic commands ###
